#+TITLE: Nordkreuz

**
#+BEGIN_QUOTE
Nordkreuz ist der größte Rechtsextremismus-Skandal Mecklenburg-Vorpommerns, seine Bedeutung reicht weit über die Landesgrenzen hinaus. Es geht um eine Gruppe von Menschen, die sich auf einen [[Tag X]] vorbereiten. Manche von ihnen bauten sich Bunker in den Garten, andere legten Munitionsverstecke an. Wieder andere bestellten Leichensäcke. Zwei Mitglieder der Gruppe, darunter ein Kriminalpolizist, sollen Feindeslisten mit Privatdaten politischer Gegner angelegt haben, um sie an jenem [[Tag X]] töten zu können. Die Bundesanwaltschaft in Karlsruhe ermittelt wegen rechtsextremen Terrorismus.

Anfangs waren es die taz und wenige anderen Medien, die Stück für Stück darlegten, dass Nordkreuz Teil eines bundesweiten Geflechts aus aktiven und ehemaligen Soldaten, Polizisten und Sicherheitskräften ist, das sich über die gesamte Bundesrepublik erstreckt, dem [[Hannibal]]-Netzwerk. Inzwischen beschäftigen sich zahlreiche Sicherheitsbehörden mit Mitgliedern und Untergruppen, wegen eines paramilitärischen Trainings, wegen illegalen Waffenbesitzes, wegen des Diebstahls von Bundeswehrbeständen. Auch [[Franco A.]] bewegte sich in diesem Netzwerk, der Bundeswehroffizier, der sich als Geflüchteter ausgegeben hat und dem die Bundesanwaltschaft vorwirft, einen oder mehrere Anschläge geplant zu haben. Die Behörden stufen A. als gefährlichen Rechtsextremisten ein.
#+END_QUOTE

https://taz.de/Rechte-Prepper-in-Mecklenburg-Vorpommern/!5728354/
