#+TITLE: Nordkreuz

** Nordkreuz nennt sich eine Gruppe von etwa 40 bis zeitweise 54 rechtsextremen deutschen Preppern, die sich auf einen erwarteten Staatszusammenbruch am „Tag X“ vorbereiten und eine folgende Massentötung von als politische Gegner betrachteten Flüchtlingshelfern geplant haben sollen. […] Nach Angaben des Gründers Marko G. vom August 2020 ist die Gruppe weiter aktiv. ([[https://www.spiegel.de/politik/deutschland/rechtsextreme-bei-polizei-und-bundeswehr-die-dunkle-seite-der-staatsmacht-a-00000000-0002-0001-0000-000172378470][src]] (ist hinter Paywall)) (Auszug aus [[https://de.wikipedia.org/w/index.php?title=Nordkreuz&oldid=205635649][Wikipedia]])
**
#+BEGIN_QUOTE
Nordkreuz ist der größte Rechtsextremismus-Skandal Mecklenburg-Vorpommerns, seine Bedeutung reicht weit über die Landesgrenzen hinaus. Es geht um eine Gruppe von Menschen, die sich auf einen [[Tag X]] vorbereiten. Manche von ihnen bauten sich Bunker in den Garten, andere legten Munitionsverstecke an. Wieder andere bestellten Leichensäcke. Zwei Mitglieder der Gruppe, darunter ein Kriminalpolizist, sollen Feindeslisten mit Privatdaten politischer Gegner angelegt haben, um sie an jenem [[Tag X]] töten zu können. Die Bundesanwaltschaft in Karlsruhe ermittelt wegen rechtsextremen Terrorismus.

Anfangs waren es die taz und wenige anderen Medien, die Stück für Stück darlegten, dass Nordkreuz Teil eines bundesweiten Geflechts aus aktiven und ehemaligen Soldaten, Polizisten und Sicherheitskräften ist, das sich über die gesamte Bundesrepublik erstreckt, dem [[Hannibal]]-Netzwerk. Inzwischen beschäftigen sich zahlreiche Sicherheitsbehörden mit Mitgliedern und Untergruppen, wegen eines paramilitärischen Trainings, wegen illegalen Waffenbesitzes, wegen des Diebstahls von Bundeswehrbeständen. Auch [[Franco A.]] bewegte sich in diesem Netzwerk, der Bundeswehroffizier, der sich als Geflüchteter ausgegeben hat und dem die Bundesanwaltschaft vorwirft, einen oder mehrere Anschläge geplant zu haben. Die Behörden stufen A. als gefährlichen Rechtsextremisten ein.
#+END_QUOTE

https://taz.de/Rechte-Prepper-in-Mecklenburg-Vorpommern/!5728354/
